apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 9000  # Use a different port that is available
      targetPort: 9000
  type: ClusterIP
