apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: your-laravel-app-image:latest  # Replace with your Laravel app's Docker image
          ports:
            - containerPort: 9000  # The port your Laravel app is listening on
          volumeMounts:
            - name: laravel-config-volume
              mountPath: /var/www/html/.env
              subPath: .env
      volumes:
        - name: laravel-config-volume
          configMap:
            name: laravel-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  .env: |
    APP_ENV=production
    APP_KEY=your-app-key
    # Laravel database settings
    DB_CONNECTION=mysql
    DB_HOST=mysql-service
    DB_PORT=3306
    DB_DATABASE=database
    DB_USERNAME=root
    DB_PASSWORD=password
